#!/usr/bin/env python3
"""6.172-style score: space utilisation and throughput on allocation traces.

MIT 6.172 project 3 grades a student allocator on traces of malloc /
realloc / free calls by two numbers per trace:
  utilisation U = peak live payload / peak memory the allocator used
  throughput  T = operations per second
and combines them into one score. Here the traces are generated by this
script (deterministic, seeded, described below), "memory used" is the
growth of the process's peak physical footprint (macOS) or resident set
(Linux) during the replay, and throughput is normalised to the system
allocator. The combined score is the geometric mean over traces of
U^w * min(T / T_system, 4)^(1-w) with w = 0.5. (The course's exact
weights and caps changed from year to year; this is the same idea, not
the official grader.)

Traces:
  binary    alternate 64 B and 448 B blocks, free all the 448 B ones, then
            allocate 512 B blocks (CS:APP binary-bal: punishes size classes
            that cannot reuse freed space for a different size)
  coalesce  waves of equal blocks freed and re-requested at twice the size
  random    random sizes 16..4096 B, random lifetimes, ~20k live blocks
  realloc   200 buffers grown by realloc in 25% steps up to 512 KiB, with
            short-lived 40 B blocks in between (realloc-bal style)
  strings   2M small strings, 85% die young, 15% live to the end
  phases    build 60 MB of log-uniform sizes 16 B..64 KiB, free 90% at
            random, then build 40 MB of 64 B..2 KiB blocks
  trees     1M 48 B nodes, half freed at random, then 500k 32 B nodes

  python3 bench/score.py --ext build/ext --out results/score
"""
import argparse
import json
import math
import os
import random
import statistics
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import run as bench  # noqa: E402

W = 0.5
T_CAP = 4.0


class Trace:
    def __init__(self):
        self.lines = []
        self.next_id = 0
        self.free_ids = []

    def new_id(self):
        if self.free_ids:
            return self.free_ids.pop()
        self.next_id += 1
        return self.next_id - 1

    def a(self, size):
        i = self.new_id()
        self.lines.append(f"a {i} {size}")
        return i

    def r(self, i, size):
        self.lines.append(f"r {i} {size}")

    def f(self, i):
        self.lines.append(f"f {i}")
        self.free_ids.append(i)

    def write(self, path):
        with open(path, "w") as fh:
            fh.write(f"# ids {self.next_id}\n")
            fh.write("\n".join(self.lines))
            fh.write("\n")


def t_binary(rng):
    t = Trace()
    small, big = [], []
    for _ in range(100000):
        small.append(t.a(64))
        big.append(t.a(448))
    for i in big:
        t.f(i)
    late = [t.a(512) for _ in range(100000)]
    for i in small + late:
        t.f(i)
    return t


def t_coalesce(rng):
    t = Trace()
    for _ in range(3):
        size, n = 4096, 8000
        while size <= 65536:
            ids = [t.a(size) for _ in range(n)]
            for i in ids:
                t.f(i)
            size, n = size * 2, n // 2
    return t


def t_random(rng):
    t = Trace()
    live = []
    for _ in range(400000):
        if live and (len(live) > 20000 or rng.random() < 0.45):
            k = rng.randrange(len(live))
            live[k], live[-1] = live[-1], live[k]
            t.f(live.pop())
        else:
            live.append(t.a(rng.randint(16, 4096)))
    for i in live:
        t.f(i)
    return t


def t_realloc(rng):
    t = Trace()
    bufs = {}
    for _ in range(200):
        bufs[t.a(16)] = [16, rng.randint(64 << 10, 512 << 10)]
    temps = []
    step = 0
    while bufs:
        for i in list(bufs):
            cur, goal = bufs[i]
            nxt = min(goal, max(cur + 16, cur * 5 // 4))
            t.r(i, nxt)
            if nxt >= goal:
                t.f(i)
                del bufs[i]
            else:
                bufs[i][0] = nxt
            temps.append(t.a(40))
        step += 1
        if step % 3 == 0:
            for j in temps:
                t.f(j)
            temps = []
    for j in temps:
        t.f(j)
    return t


def t_strings(rng):
    t = Trace()
    young = []
    old = []
    for _ in range(2000000):
        n = int(8 + rng.expovariate(1 / 30)) % 120 + 8
        i = t.a(n)
        if rng.random() < 0.15:
            old.append(i)
        else:
            young.append(i)
        if len(young) > 100:
            k = rng.randrange(len(young))
            young[k], young[-1] = young[-1], young[k]
            t.f(young.pop())
    for i in young + old:
        t.f(i)
    return t


def t_phases(rng):
    t = Trace()
    live, total = [], 0
    while total < 60 << 20:
        n = int(math.exp(rng.uniform(math.log(16), math.log(65536))))
        live.append(t.a(n))
        total += n
    rng.shuffle(live)
    cut = len(live) // 10
    for i in live[cut:]:
        t.f(i)
    live = live[:cut]
    total = 0
    while total < 40 << 20:
        n = rng.randint(64, 2048)
        live.append(t.a(n))
        total += n
    for i in live:
        t.f(i)
    return t


def t_trees(rng):
    t = Trace()
    nodes = [t.a(48) for _ in range(1000000)]
    rng.shuffle(nodes)
    for i in nodes[500000:]:
        t.f(i)
    nodes = nodes[:500000] + [t.a(32) for _ in range(500000)]
    for i in nodes:
        t.f(i)
    return t


TRACES = {"binary": t_binary, "coalesce": t_coalesce, "random": t_random, "realloc": t_realloc,
          "strings": t_strings, "phases": t_phases, "trees": t_trees}


def generate(dirpath):
    os.makedirs(dirpath, exist_ok=True)
    paths = {}
    for k, (name, fn) in enumerate(TRACES.items()):
        path = os.path.join(dirpath, name + ".rep")
        if not os.path.exists(path):
            fn(random.Random(6172 + k)).write(path)
        paths[name] = path
    return paths


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ext", default=os.path.join(ROOT, "build", "ext"))
    ap.add_argument("--out", default=os.path.join(ROOT, "results", "score"))
    ap.add_argument("--traces", default=os.path.join(ROOT, "build", "traces"))
    ap.add_argument("--reps", type=int, default=3)
    ap.add_argument("--allocs", default="system,mallockit,mimalloc,jemalloc")
    args = ap.parse_args()
    replay = os.path.join(ROOT, "build", "trace_replay")
    traces = generate(args.traces)
    allocs = {k: v for k, v in bench.allocators(args.ext).items() if k in args.allocs.split(",")}
    rows = []
    for name, path in traces.items():
        for alloc, lib in allocs.items():
            utils = []
            for _ in range(2):
                r = bench.run_measured([replay, "util", path], lib)
                if r["ok"]:
                    utils.append(json.loads(r["out"].strip().splitlines()[-1]))
            times = []
            for _ in range(args.reps):
                r = bench.run_measured([replay, "time", path, "0.3"], lib)
                if r["ok"]:
                    times.append(json.loads(r["out"].strip().splitlines()[-1])["ops_per_sec"])
            if not utils or not times:
                print(f"{name} {alloc}: FAILED", flush=True)
                continue
            u = statistics.median(x["util"] for x in utils)
            row = {"trace": name, "alloc": alloc, "util": u, "peak_payload": utils[0]["peak_payload"],
                   "mem_growth": statistics.median(x["rss_growth"] for x in utils), "ops": utils[0]["ops"],
                   "ops_per_sec": statistics.median(times), "ops_per_sec_all": times}
            rows.append(row)
            print(f"{name:9s} {alloc:9s} util {u:.3f}  {row['ops_per_sec'] / 1e6:7.1f} Mops/s", flush=True)
    sysT = {r["trace"]: r["ops_per_sec"] for r in rows if r["alloc"] == "system"}
    scores = {}
    for alloc in allocs:
        mine = [r for r in rows if r["alloc"] == alloc]
        parts = []
        for r in mine:
            rel = min(r["ops_per_sec"] / sysT[r["trace"]], T_CAP)
            r["t_rel"] = rel
            parts.append((W * math.log(max(r["util"], 1e-6)) + (1 - W) * math.log(rel)))
        if parts:
            scores[alloc] = {"score": math.exp(sum(parts) / len(parts)),
                             "util_geomean": math.exp(sum(math.log(max(r["util"], 1e-6)) for r in mine) / len(mine)),
                             "t_rel_geomean": math.exp(sum(math.log(r["t_rel"]) for r in mine) / len(mine))}
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "score.json"), "w") as fh:
        json.dump({"machine": bench.machine(), "w": W, "t_cap": T_CAP, "rows": rows, "scores": scores}, fh, indent=1)
    for alloc, s in scores.items():
        print(f"{alloc:9s} score {s['score']:.3f}  util {s['util_geomean']:.3f}  T/T_sys {s['t_rel_geomean']:.2f}")


if __name__ == "__main__":
    main()
